# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy build inputs
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN npm run build

EXPOSE 5000

CMD [ "node", "build/index.js" ]
